### ISSUE TITLE
Not getting kinesis data, help appreciated

### ISSUE THREAD

**Issue by joykabir** [logstash-plugins/logstash-input-kinesis#8]
Hi,
can anyone help me why I'm not getting stream data into logstash. Kinesis stream is subscribed to Cloudwatch log group and data is put into kinesis. All permissions are OK.
** This is config file:
cat /etc/logstash/conf.d/logstash-indexer.conf

`input {
    tcp {
        port  => 6379
        codec => json_lines
    }
    kinesis {
        kinesis_stream_name => 'elk-kinesis-ElkKinesisStream-XYZ'
        application_name => 'elk-kinesis-ElkKinesisDynamoDBTable-XYZ'
        region => 'eu-west-1'
	compression => "gzip"
        codec => json { }
    }`
}
`output {
    elasticsearch { hosts => ["localhost:9200"] 
}`

** And this is /var/log/logstash/logstash.log : 

```
{:timestamp=>"2016-10-10T09:08:16.053000+0000", :message=>"Error processing record: Input length = 1", :level=>:error}
{:timestamp=>"2016-10-10T09:08:17.041000+0000", :message=>"Error processing record: Input length = 1", :level=>:error}
{:timestamp=>"2016-10-10T09:08:58.056000+0000", :message=>"Error processing record: Input length = 1", :level=>:error}
{:timestamp=>"2016-10-10T09:09:06.095000+0000", :message=>#<LogStash::PipelineReporter::Snapshot:0x3587d74 @data={:events_filtered=>0, :events_consumed=>0, :worker_count=>2, :inflight_count=>0, :worker_states=>[{:status=>"sleep", :alive=>true, :index=>0, :inflight_count=>0}, {:status=>"sleep", :alive=>true, :index=>1, :inflight_count=>0}], :output_info=>[{:type=>"elasticsearch", :config=>{"hosts"=>["localhost:9200"], "__ALLOW_ENV__"=>false}, :is_multi_worker=>false, :events_received=>0, :workers=><Java::JavaUtilConcurrent::CopyOnWriteArrayList:-1410898713 [<LogStash::Outputs::ElasticSearch hosts=>["localhost:9200"], codec=><LogStash::Codecs::Plain charset=>"UTF-8">, workers=>1, index=>"logstash-%{+YYYY.MM.dd}", manage_template=>true, template_name=>"logstash", template_overwrite=>false, flush_size=>500, idle_flush_time=>1, doc_as_upsert=>false, max_retries=>3, script_type=>"inline", script_var_name=>"event", scripted_upsert=>false, retry_max_interval=>2, retry_max_items=>500, retry_on_conflict=>1, action=>"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5>]>, :busy_workers=>0}], :thread_info=>[{"thread_id"=>17, "name"=>"[main]<kinesis", "plugin"=>nil, "backtrace"=>["[...]/vendor/bundle/jruby/1.9/gems/logstash-input-kinesis-1.4.3-java/lib/logstash/inputs/kinesis.rb:74:in `run'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:342:in `inputworker'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:336:in `start_input'"], "blocked_on"=>nil, "status"=>"run", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-kinesis-1.4.3-java/lib/logstash/inputs/kinesis.rb:74:in `run'"}, {"thread_id"=>21, "name"=>"[main]>worker0", "plugin"=>nil, "backtrace"=>["[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `inflight_batches_synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:234:in `worker_loop'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:201:in `start_workers'"], "blocked_on"=>nil, "status"=>"sleep", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>22, "name"=>"[main]>worker1", "plugin"=>nil, "backtrace"=>["[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `inflight_batches_synchronize'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:234:in `worker_loop'", "[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:201:in `start_workers'"], "blocked_on"=>nil, "status"=>"sleep", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `synchronize'"}], :stalling_threads_info=>[{"thread_id"=>17, "name"=>"[main]<kinesis", "plugin"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-kinesis-1.4.3-java/lib/logstash/inputs/kinesis.rb:74:in `run'"}, {"thread_id"=>21, "name"=>"[main]>worker0", "plugin"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>22, "name"=>"[main]>worker1", "plugin"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:309:in `synchronize'"}]}>, :level=>:warn}
```

**Comment by codekitchen** [comment]
@joykabir your config looks like you're trying to use the cloudwatch logs functionality, which isn't merged in yet (https://github.com/logstash-plugins/logstash-input-kinesis/pull/3), did you make your own build of this gem?

**Comment by joykabir** [comment]
Hi, Thanks for reply. Yes, my kinesis stream is subscribed into several Cloudwatch Logs group.
No I have not build this gem, just installed as per guideline. Does a local build solve this?

**Comment by codekitchen** [comment]
The cloudwatch logs consuming functionality in #3 is still under development, it doesn't exist in the released version of this plugin. You can try doing a local build with that PR applied, but there's no guarantee that it'll work since it's not finished.

I'm going to close this issue, if you do end up trying it out it'd be best to report any issues you run into on #3 so that they can be addressed.
