### ISSUE TITLE
Problem with Kinesis input plugin 

### ISSUE THREAD

**Issue by rkredux** [logstash-plugins/logstash-input-kinesis#88]
I have a Logstash pipeline that uses the Kinesis input plugin which is not consuming records from the Kinesis data stream. I set the log level to DEBUG in the pipeilne to find out the issue. Found out the log below which may explain. 

Some more details: 
Logstash version - 7.9.0
Kinesis input plugin version - v2.1.1

> `[2020-09-01T03:44:56,517][DEBUG][logstash.javapipeline ][cloudwatch] Pipeline terminated by worker error {:pipeline_id=>"cloudwatch", :exception=>#<NoMethodError: undefined method `logger' for #<Java::OrgApacheLoggingLog4jJcl::Log4jLog:0x1533bdca>>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-kinesis-2.1.1-java/lib/logstash/inputs/kinesis.rb:78:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:226:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:225:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:359:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:309:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:183:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/cumulus-cloudwatch-sb-sit.conf"], :thread=>"#<Thread:0x43c79311@/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:53 run>"}`

**Comment by rkredux** [comment]
The stack trace seems to point to a problem with https://github.com/logstash-plugins/logstash-input-kinesis/blob/master/lib/logstash/inputs/kinesis.rb#L78

**Comment by rkredux** [comment]
This seems to have been resolved with the release of v2.1.2. Can be closed out. Thanks.
